### ISSUE TITLE
workflow: define schema with conditional

### ISSUE THREAD

**Issue by maximilien** [i-am-bee/bee-hive#126]
Build on issue #48 to add conditionals to steps

**Comment by maximilien** [comment]
After my proposal and discussions in #124 the result is to add conditionals as follows:

```yaml
steps:
  - name: step1
    condition:
      - if: some condition
        then: do something
        else: do something else
  - name: step2
    condition:
      - case: some condition
        do: do something
      - case: some other condition
        do: do something else
      - default:
          do: do default something
```

Will submit a PR shortly to add this to `tools/workflow_schema.json` with appropriate test files. Please comment on PR with your suggestions and fixes.

Thanks @akihikokuroda @psschwei and @developer-gliu for the discussion
