### ISSUE TITLE
Schema: define the schema for agent

### ISSUE THREAD

**Issue by maximilien** [i-am-bee/bee-hive#136]
Create the first version of the agent section for the workflow. 

```yaml

apiVersion: beehive/v1alpha1
kind: Agent
metadata:
  name: hot-or-not
  labels:
    app: mas-example
spec:
  model: meta-llama/llama-3-1-70b-instruct
  description: Is the current temperature hotter than usual?
  tools:
    - code_interpreter
    - weather
  instructions: The user will give you a temperature in Fahrenheit and a location. Use the OpenMateo weather tool to find the average monthly temperature for the location. Answer if the temperature provided by the user is hotter or colder than the average found by the tool.
```
CC: @planetf1 @akihikokuroda @psschwei
