### ISSUE TITLE
workflow language supports conditionals

### ISSUE THREAD

**Issue by psschwei** [i-am-bee/bee-hive#39]
Implement conditional workflow as function of Workflow class

**Comment by akihikokuroda** [comment]
For now, Bee-hive doesn't see any output from agents.  Seeing the output from the agent may be necessary for this.  WDYT?

**Comment by planetf1** [comment]
Have you had any thoughts about how to express conditions?

Some approaches have used preprocessing, or templating (ie helm) - but this gets away from yaml being the source

Currently we have an Agent and Workflow definition. The latter does have a strategy entry. I was wondering if we expect to add explicit task (or step, or both?) definitions within the workflow, so we end up with something more like github actions (or tekton?)

Just sketching around ?
```yaml
tasks:
  # A task is a 'unit' that probably executes with shared context?
  # is this needed?
  - name: getthenews
    # A step is an individual action that invokes an agent or similar
    steps:
      - name: current-affairs
        # explicitly refer to the agent we will invoke here
        execute: current-affairs
      - name: fact-check
        execute: fact-checker
        # introduce a condition (consider how we handle variables?)
        # this step is only used in the UK
        if: country == 'UK'
      - name: review
        # support matrix parallelism
        strategy:
          matrix:
            # we end up invoking with each value
            agent ['sme-reviewer','layperson-reviewer','investor-reviewer']
        execute: {{ matrix.agent }}
      - name: hot-or-not
        # How can we make use of variables within the executed agent? GHA uses shell script
        # where does 'number-of-hot-articles' come from? the execution must be able to modify it
        execute: hot-or-not
        until: number-of-hot-articles > 5
        # Thought - could we also use shell script? Adds variable expansion, loops etc?
        # but then that is programming ...
```

Is there a current proposal?
